# Trigger the workflow whenever changes are pushed to the deploy directory
on:
  push:
    paths:
      - 'deploy/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Make sure this is present
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.0.0
        with:
          workload_identity_provider: 'projects/175415323680/locations/global/workloadIdentityPools/githubpool/providers/github'
          service_account: github-wif-sa@properties-app-418208.iam.gserviceaccount.com

      # Step 3: Set up GKE credentials
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: simple-autopilot-public-cluster
          location: us-central1  # Adjust your cluster zone
          project_id: properties-app-418208

      # Step 4: Deploy to GKE
      - name: Deploy to GKE
        run: |
          echo "Deploying to GKE..."
          kubectl apply -f deploy/kalyanam-deployment.yaml  # Adjust the path as needed
          kubectl apply -f deploy/rsvpbackend-deployment.yaml  # Adjust the path as needed
