# Trigger the workflow whenever changes are pushed to the deploy directory
on:
  push:
    paths:
      - 'deploy/**'

jobs:
  checkout-manifests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Get the list of changed files
      - name: Get changed files
        run: |
          git fetch --depth=2
          git diff --name-only HEAD^ HEAD > changed_files.txt
          cat changed_files.txt
          echo "CHANGED_FILES=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV  # Export changed files to environment variable

  deploy:
    runs-on: ubuntu-latest
    needs: checkout-manifests  # Ensure this job runs after the checkout-manifests
    permissions:
      contents: read
      id-token: write  # Make sure this is present
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.0.0
        with:
          workload_identity_provider: 'projects/175415323680/locations/global/workloadIdentityPools/githubpool/providers/github'
          service_account: github-wif-sa@properties-app-418208.iam.gserviceaccount.com

      # Step 3: Set up GKE credentials
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: simple-autopilot-public-cluster
          location: us-central1  # Adjust your cluster zone
          project_id: properties-app-418208

      # Step 4: Deploy to GKE only for changed files
      - name: Deploy to GKE
        run: |
          for file in $CHANGED_FILES; do
            echo "Deploying $file"
            kubectl apply -f $file
          done
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}