name: 'Terraform'

on:
  push:
    branches:
      - "main"              # Match the main branch
      - "feature/**"        # Match any branch that starts with 'feature'
  pull_request:
    branches:
      - "main"              # Match pull requests targeting the main branch
      - "feature/**"        # Match any pull request targeting branches that start with 'feature'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: 'projects/175415323680/locations/global/workloadIdentityPools/githubpool/providers/github'
        service_account: github-wif-sa@properties-app-418208.iam.gserviceaccount.com

    # Run the Helm repo script
    - name: Run Helm Repo Script
      run: |
        chmod +x .github/workflows/scripts/helm-repo.sh
        .github/workflows/scripts/helm-repo.sh
         
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
   
    - name: Terraform Init
      run: terraform init
    
    # Generates a destruction plan for Terraform
    - name: Terraform Plan Destroy
      run: terraform plan -destroy -input=false

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
      
