name: 'Terraform'

on:
  push:
    branches:
      - "main"              # Match the main branch
      - "feature/**"        # Match any branch that starts with 'feature'
  pull_request:
    branches:
      - "main"              # Match pull requests targeting the main branch
      - "feature/**"        # Match any pull request targeting branches that start with 'feature'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: 'projects/175415323680/locations/global/workloadIdentityPools/githubpool/providers/github'
        service_account: github-wif-sa@properties-app-418208.iam.gserviceaccount.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


    #   # Install Google Cloud SDK
    # - name: Install Google Cloud SDK
    #   run: |
    #     echo "Installing Google Cloud SDK..."
    #     echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    #     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    #     sudo apt-get update && sudo apt-get install -y google-cloud-sdk

    # # Run the bash script to check GKE cluster status
    # - name: Check if GKE Cluster Exists
    #   run: |
    #     echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > $GOOGLE_APPLICATION_CREDENTIALS
    #     gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    #     gcloud config set project properties-app-418208
    #     chmod +x .github/workflows/scripts/check-gke-cluster.sh
    #     .github/workflows/scripts/check-gke-cluster.sh

    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    # - name: Terraform Plan
    #   run: terraform plan -input=false

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve -input=false


    # Generates a destruction plan for Terraform
    - name: Terraform Plan Destroy
      run: terraform plan -destroy -input=false

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
      
