name: 'Terraform'

on:
  push:
    branches:
      - "main"              # Match the main branch
      - "feature/**"        # Match any branch that starts with 'feature'
  pull_request:
    branches:
      - "main"              # Match pull requests targeting the main branch
      - "feature/**"        # Match any pull request targeting branches that start with 'feature'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: 'projects/175415323680/locations/global/workloadIdentityPools/githubpool/providers/github'
        service_account: github-wif-sa@properties-app-418208.iam.gserviceaccount.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Create or select the workspace based on the branch name
    - name: Set up Terraform workspace
      id: setup_workspace
      run: |
        # Set the workspace name based on the current branch
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "WORKSPACE_NAME=main" >> $GITHUB_ENV
        else
          # Replace slashes with dashes for workspace name
          WORKSPACE_NAME="${{ github.ref }}"; WORKSPACE_NAME=${WORKSPACE_NAME//\//-}
          echo "WORKSPACE_NAME=${WORKSPACE_NAME}" >> $GITHUB_ENV
        fi
        
    - name: Terraform Init
      run: |
        # use the workspace created above
        terraform workspace select $WORKSPACE_NAME || terraform workspace new $WORKSPACE_NAME
        terraform init \
          -backend-config="bucket=tf-gcp-wif-tfstate" \
          -backend-config="prefix=terraform/state/${WORKSPACE_NAME}"  # Use the workspace name in the prefix

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false


    # Generates a destruction plan for Terraform
    # - name: Terraform Plan Destroy
    #   run: terraform plan -destroy -input=false

    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve -input=false
      
